return {}
-- return {
--   'zaldih/themery.nvim',
--   lazy = false,
--   opts = {
--     themes = {
--       {
--         name = 'Retrobox Dark',
--         colorscheme = 'retrobox',
--         before = [[vim.opt.background = 'dark']],
--       },
--       {
--         name = 'Retrobox Light',
--         colorscheme = 'retrobox',
--         before = [[vim.opt.background = 'light']],
--       },
--       {
--         name = 'Randomhue Dark',
--         colorscheme = 'randomhue',
--         before = [[vim.opt.background = 'dark']],
--       },
--       {
--         name = 'Randomhue Light',
--         colorscheme = 'randomhue',
--         before = [[vim.opt.background = 'light']],
--       },
--       'solarized-osaka-storm',
--       'solarized-osaka-moon',
--       'solarized-osaka-night',
--       'solarized-osaka-day',
--       {
--         name = 'Bamboo Light',
--         colorscheme = 'bamboo-light',
--         before = [[vim.cmd'colorscheme bamboo']],
--       },
--       {
--         name = 'Bamboo Multiplex',
--         colorscheme = 'bamboo-multiplex',
--         before = [[vim.cmd'colorscheme bamboo']],
--       },
--       {
--         name = 'Bamboo Vulgaris',
--         colorscheme = 'bamboo-vulgaris',
--         before = [[vim.cmd'colorscheme bamboo']],
--       },
--       'nvimgelion',
--       'deepwhite',
--       {
--         name = 'Sweetie Dark',
--         colorscheme = 'sweetie',
--         before = [[vim.opt.background = 'dark']],
--       },
--       {
--         name = 'Sweetie Light',
--         colorscheme = 'sweetie',
--         before = [[vim.opt.background = 'light']],
--       },
--       {
--         name = 'Doom-One Dark',
--         colorscheme = 'doom-one',
--         before = [[vim.opt.background = 'dark']],
--       },
--       {
--         name = 'Doom-One Light',
--         colorscheme = 'doom-one',
--         before = [[vim.opt.background = 'light']],
--       },
--       {
--         name = 'Quiet Dark',
--         colorscheme = 'quiet',
--         before = [[vim.opt.background = 'dark']],
--       },
--       {
--         name = 'Quiet Light',
--         colorscheme = 'quiet',
--         before = [[vim.opt.background = 'light']],
--       },
--     },
--   },
-- }
